src/Entity/Account.php
<?php

namespace App\Entity;

use App\Repository\AccountRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=AccountRepository::class)
 */
class Account
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank  
     * @Assert\Type("string")
     */
    private $account_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $account_number;

    /**
     * @ORM\Column(type="datetime")
     */
    private $open_date;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $close_date;

    /**
     * @ORM\Column(type="float")
     * @Assert\Positive
     * @Assert\NotBlank
     * @Assert\GreaterThan(
     * value = 49
     *)
     */
    private $account_amount;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="accounts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity=Operation::class, mappedBy="account", orphanRemoval=true)
     */
    private $operations;

    public function __construct()
    {
        $this->operations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAccountName(): ?string
    {
        return $this->account_name;
    }

    public function setAccountName(string $account_name): self
    {
        $this->account_name = $account_name;

        return $this;
    }

    public function getAccountNumber(): ?string
    {
        return $this->account_number;
    }

    public function setAccountNumber(string $account_number): self
    {
        $this->account_number = $account_number;

        return $this;
    }

    public function getOpenDate(): ?\DateTimeInterface
    {
        return $this->open_date;
    }

    public function setOpenDate(\DateTimeInterface $open_date): self
    {
        $this->open_date = $open_date;

        return $this;
    }

    public function getCloseDate(): ?\DateTimeInterface
    {
        return $this->close_date;
    }

    public function setCloseDate(?\DateTimeInterface $close_date): self
    {
        $this->close_date = $close_date;

        return $this;
    }

    public function getAccountAmount(): ?float
    {
        return $this->account_amount;
    }

    public function setAccountAmount(float $account_amount): self
    {
        $this->account_amount = $account_amount;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Operation[]
     */
    public function getOperations(): Collection
    {
        return $this->operations;
    }

    public function addOperation(Operation $operation): self
    {
        if (!$this->operations->contains($operation)) {
            $this->operations[] = $operation;
            $operation->setAccount($this);
        }

        return $this;
    }

    public function removeOperation(Operation $operation): self
    {
        if ($this->operations->removeElement($operation)) {
            // set the owning side to null (unless already changed)
            if ($operation->getAccount() === $this) {
                $operation->setAccount(null);
            }
        }

        return $this;
    }
}

src/Entity/Operation.php
<?php

namespace App\Entity;

use App\Repository\OperationRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=OperationRepository::class)
 */
class Operation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $operation_type;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $operation_name;

    /**
     * @ORM\Column(type="float")
     * @Assert\NotBlank
     */
    private $operation_amount;

    /**
     * @ORM\Column(type="datetime")
     */
    private $operation_date;

    /**
     * @ORM\ManyToOne(targetEntity=Account::class, inversedBy="operations")
     * @ORM\JoinColumn(nullable=false)
     */
    private $account;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOperationType(): ?string
    {
        return $this->operation_type;
    }

    public function setOperationType(string $operation_type): self
    {
        $this->operation_type = $operation_type;

        return $this;
    }

    public function getOperationName(): ?string
    {
        return $this->operation_name;
    }

    public function setOperationName(string $operation_name): self
    {
        $this->operation_name = $operation_name;

        return $this;
    }

    public function getOperationAmount(): ?float
    {
        return $this->operation_amount;
    }

    public function setOperationAmount(float $operation_amount): self
    {
        $this->operation_amount = $operation_amount;

        return $this;
    }

    public function getOperationDate(): ?\DateTimeInterface
    {
        return $this->operation_date;
    }

    public function setOperationDate(\DateTimeInterface $operation_date): self
    {
        $this->operation_date = $operation_date;

        return $this;
    }

    public function getAccount(): ?Account
    {
        return $this->account;
    }

    public function setAccount(?Account $account): self
    {
        $this->account = $account;

        return $this;
    }
}

templates/bank/creditOperation.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}

{% block body %}
    <h2>Veuillez remplir les champs pour créditer votre compte</h2>
    {{ form(form) }}
{% endblock %}

templates/bank/debitOperation.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}

{% block body %}
    <h2>Veuillez remplir les champs pour débiter votre compte</h2>
    {{ form(form) }}
{% endblock %}

templates/bank/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} SymfoBank {% endblock %}

{% block body %}
    <h1 class="text-center mb-3">Vos comptes bancaires :</h1>
    <div class="container-fluid">
        <div class="row">
            {% for account in accounts %}
            <div class="card col-3 my-3 mx-5 ">
                <div class="card-header">
                    <h5 class="card-title">Compte</h5>
                    {{account.accountName}}
                </div>

                <div class="card-body">
                    <ul class="list-group list-group-flush">
                        
                        <li class="list-group-item">N° de compte : {{'FR' ~ account.accountNumber}}</li>
                    </ul>
                    <hr>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">Date d'ouverture : {{account.openDate | date('d/m/Y')}}</li>
                        <li class="list-group-item">Solde du compte : {{account.accountAmount}}</li>
                    </ul>
                </div>
                <div class="card-footer text-center">
                    <a href="{{ path('singleAccount', {id: account.id}) }}" class="card-link btn btn-dark">Voir détails</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/bank/lastOperation.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}

{% block body %}
<h2 class="text-center mb-5">Votre compte</h2>
<div class="container-fluid row">
    <div class="card m-auto col-4">
        <div class="card-header">
            {{account.accountName}}
        </div>
        <div class="card-body">
            <p class="card-text">N° de compte : {{'FR' ~ account.accountNumber}}</p>
            <hr>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Date d'ouverture : {{account.openDate | date('d/m/Y')}}</li>
                <li class="list-group-item">Solde du compte : {{account.accountAmount}}</li>
            </ul>
            <hr>
            {% if (operations) %}
            <h5 class="text-center">Dernières opérations</h5>
            {% for operation in operations %}
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Type : {{operation.operationType}}</li>
                <li class="list-group-item">Nom : {{operation.operationName}}</li>
                <li class="list-group-item">Montant : {{operation.operationAmount}}</li>
                <li class="list-group-item">Date : {{operation.operationDate | date('d/m/Y')}}</li>
            </ul>
            <hr>
            {% endfor %}
            {% else %}
            <h5 class="text-center">Pas d'opération sur ce compte</h5>
            {% endif %}
        </div>
        <div class="card-footer text-center">
            <a href="{{ path('creditOperation', {accountId:account.id}) }}" class="card-link btn btn-dark mt-0">Crédit</a>
            <a href="{{ path('debitOperation', {accountId:account.id}) }}" class="card-link btn btn-dark mt-0">Débit</a>
        </div>
    </div>
</div>
    
{% endblock %}

templates/bank/newAccount.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}

{% block body %}
    <h2>Ouvrez votre compte</h2>
    {{ form(form) }}
{% endblock %}

templates/bank/singleAccount.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}

{% block body %}
<h2 class="text-center mb-5">Votre compte</h2>
<div class="container-fluid row">
    <div class="card m-auto col-4">
        <div class="card-header">
            {{account.accountName}}
        </div>
        <div class="card-body">
            <p class="card-text">N° de compte : {{'FR' ~ account.accountNumber}}</p>
            <hr>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Date d'ouverture : {{account.openDate | date('d/m/Y')}}</li>
                <li class="list-group-item">Solde du compte : {{account.accountAmount}}</li>
            </ul>
            <hr>
            <h5 class="text-center">Dernières opérations</h5>
            <ul class="list-group list-group-flush">
                <a href="{{ path('lastOperation', {accountId:account.id}) }}" class="card-link btn btn-dark mt-0">Voir opérations</a>
            </ul>
            <hr>
        </div>
        <div class="card-footer text-center">
            <a href="{{ path('creditOperation', {accountId:account.id}) }}" class="card-link btn btn-dark mt-0">Crédit</a>
            <a href="{{ path('debitOperation', {accountId:account.id}) }}" class="card-link btn btn-dark mt-0">Débit</a>
        </div>
    </div>
</div>
    
{% endblock %}